---

# INVENTORY ITEM CONFIGURATION

# This is the world / level you want the inventory item to be present in.
world: world

# You can change the position of the rose inventory item which opens the cosmetics menu here.
# The inventory numbers go as follows: https://i.ibb.co/nr4GdPP/image.png
inventorySlot: 4

# This the inventory item's name.
# Available color codes: https://www.digminecraft.com/lists/sign_color_list_bedrock.php
# Leave blank to have no item name.
itemName: "§gCOSMETICS"

# This is the item itself. You can checkout all the item IDs at: https://www.digminecraft.com/lists/item_id_list_pe.php
# Default item is a Poppy (Item ID: 38).
itemId: 38
...
